name: "PR Changes"
description: "Get all changes from a PR"
inputs:
  pr-number:
    description: "PR number"
    required: true
  GITHUB_TOKEN:
    description: "github token"
    required: true
outputs:
  changes:
    description: "Changes in the PR"
runs:
  using: "node16"
  main: "index.js"
